server {
    listen       27080;
    #server_name  localhost;

    location /sso/tgc {
        # 允许所有域名跨域, cookie 需要跨域后端 https + (secure, sameSite=None)
        add_header 'Access-Control-Allow-Origin' $http_origin;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Authorization,DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        add_header Access-Control-Allow-Credentials 'true';
        # 处理 OPTIONS 预检请求
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }
        set $cookie_value "";
        add_header Content-Type text/plain;
        if ($http_cookie ~* "(^|;\s*)TGC=([^;]*)") {
            set $cookie_value $2;
        }
        return 200 $cookie_value;
    }

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://127.0.0.1:37080;
    }
}


server {
    listen 80;
    server_name example.com;

    location / {
        # CORS headers
        # 动态域名配置
        # add_header 'Access-Control-Allow-Origin' $http_origin;
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        # 允许携带 Cookie
        add_header 'Access-Control-Allow-Credentials' 'true';

        # Handle preflight requests (OPTIONS)
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }

        # Proxy or serve files
        proxy_pass http://backend;
    }

}