networks:
  rabbitmq-network:
    driver: bridge

services:
  rabbitmq-server:
    image: rabbitmq:3.13.7-management
    container_name: rabbitmq-server
    hostname: rabbitmq-server
    environment:
      # 默认用户名密码
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      # 启用管理插件
      RABBITMQ_DEFAULT_VHOST: "/"
      # Optional tuning
      RABBITMQ_ERLANG_COOKIE: "my_secret_cookie_618512cc090a990423207be5"
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Web UI
    volumes:
      # mkdir -p ./rabbitmq/{data,logs,plugins,conf}
      # chown -R 999:999 ./rabbitmq
      #- ./rabbitmq/init.sh:/init.sh
      # https://github.com/rabbitmq/rabbitmq-delayed-message-exchange 
      # 从 4.3+ 版本开始，RabbitMQ 官方已经内置了 rabbitmq_delayed_message_exchange 插件，无需单独安装。
      # rabbitmq-plugins enable rabbitmq_delayed_message_exchange
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/logs:/var/log/rabbitmq
      - ./rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.13.0.ez:/opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.13.0.ez
      - ./rabbitmq/conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/conf/definitions.json:/etc/rabbitmq/definitions.json
    user: "999:999"  # 指定 RabbitMQ 的用户 ID
    # /bin/sh /opt/rabbitmq/sbin/rabbitmq-server
    # command: /bin/bash -c "rabbitmq-plugins enable rabbitmq_delayed_message_exchange ; rabbitmq-server"
    command:
      - bash
      - -c
      - |
        rabbitmq-plugins enable rabbitmq_delayed_message_exchange
        rabbitmq-server
    restart: always
    networks:
      - rabbitmq-network