FROM openjdk:8-jdk-slim

# openjdk:17-jdk         # 完整版(基于Debian)
# openjdk:17-jdk-slim    # 精简版(基于Debian Slim)

# openjdk:8-jdk -> debain 11(bullseye)
# openjdk:11-jdk -> debain 11(bullseye)
# openjdk:17-jdk -> debain 11(bullseye)

# jdk8 -> 1.8.0_342

COPY ./debian11.sources /etc/apt/sources.list.d/debian.sources

RUN cp /etc/apt/sources.list /etc/apt/sources.list.backup \
    && echo "" > /etc/apt/sources.list \
    && apt-get update -y \
    && apt-get install -y curl vim iputils-ping locales procps htop telnet tzdata \
    && sed -i 's/# zh_CN.UTF-8 UTF-8/zh_CN.UTF-8 UTF-8/ ; s/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && locale-gen \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV TERM=xterm
ENV TZ=Asia/Shanghai
ENV LANG=en_US.UTF-8

WORKDIR /opt/

CMD ["java", "-version"]
